version: '3'
services:
  nft-minter:
    image: nft-minter
    build: 
      context: .
      dockerfile: ./infra/.dockerfile
    ports: 
      - "3000:3000"
    networks:
      - localhost
networks:
  localhost: {}