name:

on:
  release:
    types: [published]
jobs:
  build-image:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get tag
        run: |
          tag=$(echo "${{ github.ref }}")
          echo "Tag: ${tag}"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: make build-image
      - name: Tag Docker image
        run: docker tag nft-minter sramirezpch/nft-minter
      - name: Push Docker image to Docker Hub
        run: |
          docker push sramirezpch/nft-minter
