name: CI

on:
  pull_request:
    branches:
      - "master"
jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Build image
        run: make build-image
  run-tests:
    name: Run component unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
